included:
  - Shared
  - Resources
  - Extensions
  - GameLogic
  - Environment
  - Palettes
  - Misc
  - WordlikeTests
  - macOS

excluded:
  - DerivedData
  - .build
  - build

opt_in_rules:
  - collection_alignment
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - enum_case_associated_values_count
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - flatmap_over_map_reduce
  - identical_operands
  - last_where
  - literal_expression_end_indentation
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unowned_variable_capture

disabled_rules:
  - trailing_whitespace
  - todo
  - opening_brace
  - colon
  - return_arrow_whitespace
  - redundant_type_annotation
  - operator_usage_whitespace
  - implicit_optional_initialization
  - control_statement
  - private_over_fileprivate
  - implicit_return
  - closure_parameter_position
  - trailing_comma
  - redundant_discardable_let
  - vertical_whitespace
  - trailing_newline
  - extension_access_modifier
  - void_return
  - multiple_closures_with_trailing_closure
  - comma
  - syntactic_sugar
  - vertical_parameter_alignment_on_call
  - switch_case_alignment
  - unused_closure_parameter
  - legacy_random
  - closure_spacing
  - for_where
  - statement_position
  - comment_spacing
  - vertical_parameter_alignment
  - large_tuple
  - force_try
  - unneeded_parentheses_in_closure_argument
  - closure_end_indentation
  - yoda_condition
  - redundant_void_return
  - no_space_in_method_call
  - legacy_multiple
  - joined_default_parameter
  - first_where
  - empty_parentheses_with_trailing_closure
  - empty_enum_arguments
  - duplicate_imports
  - contains_over_first_not_nil
  - contains_over_filter_count
  - overridden_super_call
  - nesting
  - modifier_order
  - explicit_init
  - empty_string
  - cyclomatic_complexity
  - block_based_kvo
  - empty_count
  - prefer_self_in_static_references

line_length:
  warning: 350
  error: 400

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 700
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_name:
  min_length: 2
  max_length: 70
  allowed_symbols:
    - _
  validates_start_with_lowercase: false
  excluded:
    - sheetWithDetentsViewModifier

identifier_name:
  min_length: 1
  allowed_symbols:
    - _
  validates_start_with_lowercase: false

reporter: xcode
